(function() {var implementors = {};
implementors["dynasm"] = [{text:"impl&lt;'a&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/struct.State.html\" title=\"struct dynasm::State\">State</a>&lt;'a&gt;",synthetic:true,types:["dynasm::State"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/struct.DynasmData.html\" title=\"struct dynasm::DynasmData\">DynasmData</a>",synthetic:true,types:["dynasm::DynasmData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/struct.DummyArch.html\" title=\"struct dynasm::arch::DummyArch\">DummyArch</a>",synthetic:true,types:["dynasm::arch::DummyArch"]},{text:"impl&lt;'a, 'b&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/x64/struct.Context.html\" title=\"struct dynasm::arch::x64::Context\">Context</a>&lt;'a, 'b&gt;",synthetic:true,types:["dynasm::arch::x64::Context"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/x64/struct.Archx64.html\" title=\"struct dynasm::arch::x64::Archx64\">Archx64</a>",synthetic:true,types:["dynasm::arch::x64::Archx64"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/x64/struct.Archx86.html\" title=\"struct dynasm::arch::x64::Archx86\">Archx86</a>",synthetic:true,types:["dynasm::arch::x64::Archx86"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"dynasm/arch/x64/enum.X86Mode.html\" title=\"enum dynasm::arch::x64::X86Mode\">X86Mode</a>",synthetic:true,types:["dynasm::arch::x64::X86Mode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/x64/x64data/struct.Flags.html\" title=\"struct dynasm::arch::x64::x64data::Flags\">Flags</a>",synthetic:true,types:["dynasm::arch::x64::x64data::Flags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"dynasm/arch/x64/x64data/struct.Features.html\" title=\"struct dynasm::arch::x64::x64data::Features\">Features</a>",synthetic:true,types:["dynasm::arch::x64::x64data::Features"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
