[package]
name = "dynasmrt"
version.workspace = true
authors.workspace = true
edition.workspace = true

description = "A simple runtime for assembling code at runtime. Combined with the plugin crate dynasm it can be used to write JIT compilers easily."

documentation.workspace = true
repository.workspace = true

readme.workspace = true
keywords.workspace = true
license.workspace = true


[dependencies]
memmap2 = { version = "^0.5", optional = true }
byteorder = { version = "1", default-features = false }
fnv = "1.0.3"
dynasm = { version = "=2.0.0", path = "../plugin" }
lock_api = { version = "0.4.9", features = ["arc_lock"], optional = true }

[features]
default = ["std", "mmap"]
std = ["dynasm/std", "byteorder/std"]
mmap = ["memmap2", "std"]
lock_api = ["dep:lock_api"]