[package]
name = "dynasmrt"
version = "1.2.3" # remember to update dynasm dependency
authors = ["Alexander Stocko <as@coder.gg>", "CensoredUsername <cens.username@gmail.com>"]
edition = "2018"

description = "A simple runtime for assembling code at runtime. Combined with the plugin crate dynasm it can be used to write JIT compilers easily."

documentation = "https://censoredusername.github.io/dynasm-rs/plugin/dynasm/index.html"
repository = "https://github.com/CensoredUsername/dynasm-rs"

readme = "../README.md"
keywords = ["jit", "dynasm", "dynasmrt", "dynasm-rs", "assembler"]
license = "MPL-2.0"


[dependencies]
memmap2 = "^0.5"
byteorder = "1"
dynasm = { version = "=1.2.3", path = "../plugin" }
