[package]
name = "testing"
version = "0.1.0"
authors = ["Alexander Stocko <as@coder.gg>", "CensoredUsername <cens.username@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.5.*"

[dependencies.dynasmrt]
path = "../runtime"
