[package]
name = "testing"
version = "0.1.0"
authors = ["Alexander Stocko <as@coder.gg>"]

[dependencies]
itertools = "0.5.*"

[dependencies.dynasm]
path = "../plugin"

[dependencies.dynasmrt]
path = "../runtime"
