[package]
name = "insref"
version = "0.1.0"
authors = ["Alexander Stocko <as@coder.gg>", "CensoredUsername <cens.username@gmail.com>"]

[dependencies]

[dependencies.dynasm]
path = "../../plugin"
features = ["dynasm_opmap"]