[package]
name = "hello-world"
version = "0.0.1"
authors = ["CensoredUsername <cens.username@gmail.com>"]

[dependencies]

[dependencies.dynasm]
path = "../../../plugin"

[dependencies.dynasmrt]
path = "../../../runtime"
