(function() {var implementors = {};
implementors["dynasm"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/hir/def_id/struct.CrateNum.html\" title=\"struct rustc::hir::def_id::CrateNum\">CrateNum</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/hir/struct.ItemLocalId.html\" title=\"struct rustc::hir::ItemLocalId\">ItemLocalId</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/mir/struct.Local.html\" title=\"struct rustc::mir::Local\">Local</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/mir/struct.BasicBlock.html\" title=\"struct rustc::mir::BasicBlock\">BasicBlock</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/mir/struct.Field.html\" title=\"struct rustc::mir::Field\">Field</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/mir/struct.VisibilityScope.html\" title=\"struct rustc::mir::VisibilityScope\">VisibilityScope</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/rustc/mir/struct.Promoted.html\" title=\"struct rustc::mir::Promoted\">Promoted</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html\" title=\"trait rustc_data_structures::indexed_vec::Idx\">Idx</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/syntax/ast/struct.NodeId.html\" title=\"struct syntax::ast::NodeId\">NodeId</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
