[package]
name = "bf-jit"
version = "0.0.1"
authors = ["CensoredUsername <cens.username@gmail.com>"]

[dependencies]
itertools = "0.4.*"

[dependencies.dynasm]
path = "../../../plugin"

[dependencies.dynasmrt]
path = "../../../runtime"
