[package]
name = "bf-jit"
version = "0.1.0"
authors = ["CensoredUsername <cens.username@gmail.com>"]
edition = "2018"

[[bin]]
name = "x64"
path = "src/x64.rs"

[[bin]]
name = "aarch64"
path = "src/aarch64.rs"

[dependencies]
itertools = "0.5.*"

[dependencies.dynasmrt]
path = "../../../runtime"
