[package]
name = "bf-jit"
version = "0.1.0"
authors = ["CensoredUsername <cens.username@gmail.com>"]

[dependencies]
itertools = "0.5.*"

[dependencies.dynasm]
path = "../../../plugin"

[dependencies.dynasmrt]
path = "../../../runtime"
